# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"1\n\x05Point\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0e\n\x06weight\x18\x03 \x01(\x01\"2\n\x0eHeatmapRequest\x12 \n\x06points\x18\x01 \x03(\x0b\x32\x10.analytics.Point\";\n\x0fHeatmapResponse\x12(\n\x0e\x64\x65nsity_points\x18\x01 \x03(\x0b\x32\x10.analytics.Point2]\n\x10SpatialAnalytics\x12I\n\x10\x43\x61lculateHeatmap\x12\x19.analytics.HeatmapRequest\x1a\x1a.analytics.HeatmapResponseB\x1eZ\x1c./internal/transport/grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034./internal/transport/grpc/pb'
  _globals['_POINT']._serialized_start=30
  _globals['_POINT']._serialized_end=79
  _globals['_HEATMAPREQUEST']._serialized_start=81
  _globals['_HEATMAPREQUEST']._serialized_end=131
  _globals['_HEATMAPRESPONSE']._serialized_start=133
  _globals['_HEATMAPRESPONSE']._serialized_end=192
  _globals['_SPATIALANALYTICS']._serialized_start=194
  _globals['_SPATIALANALYTICS']._serialized_end=287
# @@protoc_insertion_point(module_scope)
